// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_PRSo0Mp-WIpcXl1wjbl_ktb-w7dW8E',
    appId: '1:569546616301:web:05dc083b1a2dfb659c4be4',
    messagingSenderId: '569546616301',
    projectId: 'proyecto-movil-7e4ed',
    authDomain: 'proyecto-movil-7e4ed.firebaseapp.com',
    storageBucket: 'proyecto-movil-7e4ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySuqyupeTyFM5DFwvi-XxZQVGU-qpH78',
    appId: '1:569546616301:android:36933783581048f39c4be4',
    messagingSenderId: '569546616301',
    projectId: 'proyecto-movil-7e4ed',
    storageBucket: 'proyecto-movil-7e4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOW08XeS7xmhoJuEQgAPdH-Ru7ITeo0gA',
    appId: '1:569546616301:ios:e0f17349d1477d789c4be4',
    messagingSenderId: '569546616301',
    projectId: 'proyecto-movil-7e4ed',
    storageBucket: 'proyecto-movil-7e4ed.appspot.com',
    iosClientId: '569546616301-scv220rm83i25osll43dli7gv25lagj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOW08XeS7xmhoJuEQgAPdH-Ru7ITeo0gA',
    appId: '1:569546616301:ios:e0f17349d1477d789c4be4',
    messagingSenderId: '569546616301',
    projectId: 'proyecto-movil-7e4ed',
    storageBucket: 'proyecto-movil-7e4ed.appspot.com',
    iosClientId: '569546616301-scv220rm83i25osll43dli7gv25lagj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );
}
